version: '3.8'

services:
  # Spring backend service
  spring-backend:
    build: ./spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - app-network

  # React frontend service
  react-frontend:
    build: ./reactjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - spring-backend
    networks:
      - app-network

  # Python FastAPI service
  python-api:
    build: ./python-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
